### ISSUE TITLE
Songs with no lyrics cause the script to stop, even when switching songs

### ISSUE THREAD

**Issue by SirArya** [NassimMansouri/Spotify-Lyrics-to-Discord-Status#1]
Hi,

I have been wanting something like this for a long time and I am thankful for the script. 

[Edit] Songs that do not have lyrics on Spotify cause the script to stop working and I have to restart the script in order for it to function again. (I have tried switching songs but the script will not work until I restart it)

[UPDATE] The script also seems to stop when a song gets paused and as a result it needs to be restarted again

Also every time I want launch the script I have to redo the SPOTIPY_CLIENT_ID, SPOTIPY_CLIENT_SECRET, SPOTIPY_REDIRECT_URI. Is there a way to save it so I don't have to write it every time?

If you know any potential solutions, I would appreciate it greatly.
Btw great script,
Yours Sincerely,
Arya

**Comment by Graychii** [comment]
Hey, 

Thank you for pointing these out they've been fixed now.

To set those variables permenantly : 

-If you're on windows : 
Instead of 
'set SPOTIPY_CLIENT_ID={Your_Id}'
use
'setx SPOTIPY_CLIENT_ID {Your_Id} /m'
Make sure to replace = with a space ' '

-If you're on Linux you can add it to your shell configuration file, e.g., $HOME/.bashrc or more globally in /etc/environment.

**Comment by SirArya** [comment]
Perfect, thank you for the project!
